---
title: Sam Kapila
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  food:
    title: food
    output: true
    Ingredients:
    - 
email: your-email@domain.com
description: Sam Kapila is a design and educator in Austin, TX. Sam writes and speaks
  about Responsive Web Design, design strategy, and research, and diversity and inclusion
  in tech. She is the Director of Academic Operations and Diversity at The Iron Yard,
  and taught at Texas State University for six years before that.
baseurl: 
url: 
twitter_username: samkap
github_username: samkap
markdown: kramdown
theme: minima
sass:
  style: compressed
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
date_format: "%b %-d, %Y"
logo-image: "/img/ampersam.svg"
nav-breaking-point: 520px
paginate_path: "/page-:num/"
