---
title: Sam Kapila
timezone: America/Chicago
port: 4444
collections:
  clips:
    title: Clips
    output: true
    permalink: clips/:year/:month/:day/:title
    values:
      layout: posts
  food:
    title: Food
    output: true
    permalink: food/:year/:month/:day/:title
  posts:
    title: Posts
    output: true
    layout: post
    values:
      layout: posts
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Sam Kapila is a design and educator in Austin, TX. Sam writes and speaks
  about Responsive Web Design, design strategy, and research, and diversity and inclusion
  in tech. She a former Director of Academic Operations and Diversity and university
  design instructor.
baseurl:
url: http://samkapila.com
twitter_username: samkap
github_username: samkap
markdown: kramdown
kramdown:
  parse_block_html: true
  gfm_quirks: paragraph_end
  html_to_native: false
theme: minima
sass:
  style: compressed
gems:
- jekyll-feed
- jekyll-twitter-plugin
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
date_format: "%b %-d, %Y"
logo-image: "/img/ampersam.svg"
nav-breaking-point: 520px
paginate_path: "/page-:num/"
sitemap:
  filename: "/sitemap.xml"
  exclude:
  - "/atom.xml"
  - "/feed.xml"
  - "/feed/index.xml"
  include_posts:
  - "/index.html"
  - "/clips/index.md"
  change_frequency_name: change_frequency
  priority_name: priority
